# Generated by Django 3.2.9 on 2021-12-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='due_days',
        ),
    ]
