# Generated by Django 3.2.9 on 2021-12-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_rename_due_date_invoice_due_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
