# Generated by Django 3.2.9 on 2021-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20211214_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, to='invoice.Item'),
        ),
    ]
