# Generated by Django 3.2.9 on 2021-12-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
