# Generated by Django 3.2.9 on 2021-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20211215_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
