# Generated by Django 3.2.9 on 2021-12-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20211215_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
