# Generated by Django 3.2.9 on 2021-12-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20211217_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, default='st', max_length=200, null=True),
        ),
    ]
