# Generated by Django 3.2.9 on 2021-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rot',
            field=models.BooleanField(default=False),
        ),
    ]
