# Generated by Django 4.0.4 on 2022-08-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_invoice_rot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='social_security',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invoice.customer'),
        ),
    ]
